apiVersion: apps/v1
kind: Deployment
metadata:
  name: splash
  labels:
    app: splash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splash
  template:
    metadata:
      labels:
        app: splash
    spec:
      containers:
        - name: splash
          image: "scrapinghub/splash:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: proxy-profiles
              mountPath: "/etc/splash/proxy-profiles"
          args:
            - "--max-timeout"
            - {{ .Values.splash.timeout }}
      volumes:
        - name: proxy-profiles
          configMap:
            name: {{ .Release.Name }}-configmap
