apiVersion: apps/v1
kind: Deployment
metadata:
  name: splash
  labels:
    app: splash
spec:
  replicas: 100
  selector:
    matchLabels:
      app: splash
  template:
    metadata:
      labels:
        app: splash
    spec:
      containers:
        - name: splash
          image: "scrapinghub/splash:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: "proxy-profiles"
              mountPath: "/etc/splash/proxy-profiles"
          args:
            - "--max-timeout"
            - {{ quote .Values.splash.timeout }}
            - "--disable-browser-caches"
            - "--disable-lua-sandbox"
      volumes:
        - name: "proxy-profiles"
          configMap:
            name: {{ .Release.Name }}-configmap
