apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-proxy
  labels:
    app: tor-proxy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: tor-proxy
  template:
    metadata:
      labels:
        app: tor-proxy
    spec:
      containers:
        - name: tor-proxy
          image: "dperson/torproxy:latest"
          imagePullPolicy: IfNotPresent
